services:
  app:
    build:
      context: .
    environment:
      PUBLIC_APP_NAME: gitsky
      PUBLIC_USE_MOCKS: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "pnpm run build && pnpm run preview"
